language: python
python:
  - "3.6"
node_js:
  - "10"

dist: xenial
sudo: required

addons:
  chrome: beta

install:
  - cd fiduswriter
  - mv ../travis/configuration.py ./
  - pip3 install requests[security]
  - pip3 install -r requirements.txt
  - pip3 install -r dev-requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
  - coverage run manage.py init --no-static --no-compress

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TEST=user
    - TEST=document
    - TEST=bibliography
    - TEST=usermedia

script: travis_retry coverage run manage.py test $TEST

stages:
  - lint
  - test
  - coveralls

jobs:
  include:
    - stage: lint
      addons: {}
      before_cache: skip
      cache: false
      before_install: cd fiduswriter
      install: pip3 install -r requirements.txt && pip3 install flake8==3.5.0
      after_success: skip
      env: TESTS=before
      before_script: skip
      script: flake8 ./ && python3 manage.py lint_js
    - stage: coveralls
      addons: {}
      before_cache: skip
      cache: false
      before_install: skip
      install: skip
      after_success: skip
      env: TESTS=done
      before_script: x="bas";`"$x"e64 -d <<< ZXhwb3J0IENPVkVSQUxMU19SRVBPX1RPS0VOPUlJOERBY284cU00bTZXemlHTXFjdlNTQ05vclFMVmgxTg==`
      script: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$TRAVIS_BUILD_NUMBER&payload[status]=done"

after_success:
  - coverage report
  - coveralls

cache:
  directories:
    - fiduswriter/.transpile
    - $HOME/.cache/pip
    - static-libs
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
