// This file is auto-generated. CHANGES WILL BE OVERWRITTEN! Re-generate by running ./manage.py bundle_mathlive.
export const mathliveOpfIncludes = `
<item id="mathlive-0" href="mathlive.css" media-type="text/css" />
<item id="mathlive-1" href="fonts/.DS_Store" media-type="application/octet-stream" />
<item id="mathlive-2" href="fonts/KaTeX_Main-BoldItalic.woff2" media-type="application/octet-stream" />
<item id="mathlive-3" href="fonts/KaTeX_Math-BoldItalic.woff" media-type="application/octet-stream" />
<item id="mathlive-4" href="fonts/KaTeX_SansSerif-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-5" href="fonts/KaTeX_Main-Bold.woff2" media-type="application/octet-stream" />
<item id="mathlive-6" href="fonts/KaTeX_Size2-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-7" href="fonts/KaTeX_SansSerif-Bold.woff2" media-type="application/octet-stream" />
<item id="mathlive-8" href="fonts/KaTeX_Main-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-9" href="fonts/KaTeX_Size4-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-10" href="fonts/KaTeX_Size1-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-11" href="fonts/KaTeX_Math-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-12" href="fonts/KaTeX_SansSerif-Italic.woff2" media-type="application/octet-stream" />
<item id="mathlive-13" href="fonts/KaTeX_Main-Bold.woff" media-type="application/octet-stream" />
<item id="mathlive-14" href="fonts/KaTeX_AMS-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-15" href="fonts/KaTeX_Size3-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-16" href="fonts/KaTeX_Script-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-17" href="fonts/KaTeX_SansSerif-Italic.woff" media-type="application/octet-stream" />
<item id="mathlive-18" href="fonts/KaTeX_Fraktur-Bold.woff" media-type="application/octet-stream" />
<item id="mathlive-19" href="fonts/KaTeX_Main-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-20" href="fonts/KaTeX_Fraktur-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-21" href="fonts/KaTeX_SansSerif-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-22" href="fonts/KaTeX_Typewriter-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-23" href="fonts/KaTeX_Size2-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-24" href="fonts/KaTeX_AMS-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-25" href="fonts/KaTeX_Caligraphic-Bold.woff2" media-type="application/octet-stream" />
<item id="mathlive-26" href="fonts/KaTeX_Math-BoldItalic.woff2" media-type="application/octet-stream" />
<item id="mathlive-27" href="fonts/KaTeX_Typewriter-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-28" href="fonts/KaTeX_Caligraphic-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-29" href="fonts/KaTeX_SansSerif-Bold.woff" media-type="application/octet-stream" />
<item id="mathlive-30" href="fonts/KaTeX_Script-Regular.woff2" media-type="application/octet-stream" />
<item id="mathlive-31" href="fonts/KaTeX_Caligraphic-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-32" href="fonts/KaTeX_Math-Italic.woff" media-type="application/octet-stream" />
<item id="mathlive-33" href="fonts/KaTeX_Size1-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-34" href="fonts/KaTeX_Math-Italic.woff2" media-type="application/octet-stream" />
<item id="mathlive-35" href="fonts/KaTeX_Caligraphic-Bold.woff" media-type="application/octet-stream" />
<item id="mathlive-36" href="fonts/KaTeX_Main-Italic.woff2" media-type="application/octet-stream" />
<item id="mathlive-37" href="fonts/KaTeX_Main-Italic.woff" media-type="application/octet-stream" />
<item id="mathlive-38" href="fonts/KaTeX_Math-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-39" href="fonts/KaTeX_Size4-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-40" href="fonts/KaTeX_Fraktur-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-41" href="fonts/KaTeX_Size3-Regular.woff" media-type="application/octet-stream" />
<item id="mathlive-42" href="fonts/KaTeX_Main-BoldItalic.woff" media-type="application/octet-stream" />
<item id="mathlive-43" href="fonts/KaTeX_Fraktur-Bold.woff2" media-type="application/octet-stream" />
`